### PR TITLE
Normal maps

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This PR add

- Normal map texture
- Example showing the effect of the normal map

Center: Color only
Left: Color, roughness, ambient occulsion 
Right: Color, roughness, ambient occulsion, normal map

Screenshot 2022-01-06 at 11 30 20

### CODE REVIEW

**Review by Lowentwickler — COMMENTED** [review]
Amazing, the only problem is that `demo` example does not work:
```
cargo run --release --example demo
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/examples/demo`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[9.785476 ERROR]()(no module): Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr::solid`
    error matching VERTEX shader requirements against the pipeline
    location[3] Float32x3 interpolated as Some(Perspective) with sampling Some(Center) is not provided by the previous stage outputs
    input is not provided by the earlier stage in the pipeline

', /home/elias/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Most likely because the terrain mesh is not created with all necessary attributes.

**Comment by QuantumEntangledAndy** [comment]
Ah I missed that I'll add the attributes

**Comment by QuantumEntangledAndy** [comment]
There are a current optimisations that could be done:
- Currently I calculate the bitangent on cpu this could be done cheaply on the gpu, which would saving a gpu bind op and a cpu calculate op
- Could also reduce computations in the frag shading by moving lighting data into the vertex shader (which dosent' run as often) then moving the lighting coordinates into tangent space rather than the per fragment normals into tagent space

Quality changes:
- Could do a Gram-Schmidt reorthonalisation to ensure tangent space is orthogonal

**Comment by QuantumEntangledAndy** [comment]
Demo should be fixed

**Review by Lowentwickler — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
