### PR TITLE
Horizontal scroll

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This adds horizontal scroll to the input.

I rather like blenders trackpad controls using the horizontal scroll so I wanted this for my app.

p.s. I use rustfmt by default in my editor and that makes a lot of changes. Would you be ok with putting the whole project through rustfmt or should I look to disabling that?

### CODE REVIEW

**Comment by Lowentwickler** [comment]
I am ok with `rustfmt`, even wanted to put it into CI. Would be nice to have it in one separate commit though.

**Comment by QuantumEntangledAndy** [comment]
I have a CI script for rustfmt and clippy a use in another project. Shall I put it in?

**Comment by Lowentwickler** [comment]
It would be very kind of you :)

**Comment by QuantumEntangledAndy** [comment]
Do you use tap to click on your mac's touch pad? The egui dosen't seem to like tap to click for buttons only actual clicks.

I put a couple of debug prints in and found that when using tap to click the state of the button is `Deactivated` while egui expects it to be `Hold` with this line `pressed: button_state == InputState::Hold,`. I think perhaps tap to click just sends the button up event and no other

**Comment by Lowentwickler** [comment]
Can it be that TAP triggers a separate event that we ignore?

**Comment by QuantumEntangledAndy** [comment]
From the looks of it tap just sends mouse up. Which I thinnk is normal, consider what happens when you click a hyper link on a webpage: You can click it drag the mouse away and letgo and the hyper link won't activate. Only the mouse up event triggers the link event

**Comment by QuantumEntangledAndy** [comment]
Have you also noticed how if you have an egui side bar (like in the lights demo) and you click and drag to move the camera it will also resize the side bar if your drag goes in that area.

I suspect that if would also drag scroll bars etc

**Comment by QuantumEntangledAndy** [comment]
Perhaps egui needs a global context of active ui element

**Comment by QuantumEntangledAndy** [comment]
Here's a video showing what I mean

https://user-images.githubusercontent.com/13386481/148160403-ed996f25-2950-4b90-9ea8-48890caded49.mp4

**Comment by QuantumEntangledAndy** [comment]
I am thinking it needs to handle mouse down and up fully rather than just have a yes/no for pressed.

I think this covers it:
- mouse down
  - if no active element: make element active and send mouse down
  - if active element: make new element active send new element mouse down
    - corner case of what to do with current element: send some sort of cancel command this should perhaps make buttons go out of depressed state but not click
- mouse up
  - if no active element: send mouse up
  - if active element: if active element is the same as this element send mouse up, if not send cancel to active element. Clear active element
- mouse hold:
  - if active element: send event to that element

Any thought?

**Comment by QuantumEntangledAndy** [comment]
Hmm I see you are delgating to https://github.com/emilk/egui for the lifting. I'll look into there and see what can be done

**Comment by QuantumEntangledAndy** [comment]
It seems we want to use this function:

https://github.com/emilk/egui/blob/b1fd6a44e82c8cde7fab0b952851d2d2fd785349/egui/src/context.rs#L743-L750

```rust
    /// True if egui is currently interested in the pointer (mouse or touch).
    /// Could be the pointer is hovering over a [`Window`] or the user is dragging a widget.
    /// If `false`, the pointer is outside of any egui area and so
    /// you may be interested in what it is doing (e.g. controlling your game).
    /// Returns `false` if a drag started outside of egui and then moved over an egui area.
    pub fn wants_pointer_input(&self) -> bool {
        self.is_using_pointer() || (self.is_pointer_over_area() && !self.input().pointer.any_down())
    }
```

**Comment by QuantumEntangledAndy** [comment]
Ok so I made some more changes and have it working.

- It stops egui from reacting to mouse clicks started outside
- It allows egui to respond to mouse events other than `Hold` so that tap to click works
- It adds method to egui so that end users can know when mouse clicks/keyboard is wanted by the gui (so that it won't process them in the game)
  - This was added to the lights demo to exemplify this

https://user-images.githubusercontent.com/13386481/148176542-2235d1ab-5d50-47cb-86a6-72da6afabee1.mp4

**Review by Lowentwickler — APPROVED** [review]
The example looks good to me. There is still issue, that you can rotate the camera with mouse even if mouse is above he UI. But I would fix it separately and globally.

**Comment by QuantumEntangledAndy** [comment]
> The example looks good to me. There is still issue, that you can rotate the camera with mouse even if mouse is above he UI. But I would fix it separately and globally.

Do you mean when the click starts outside the ui? That was intentional, I expect that if my click starts with controlling the camera it keeps doing that until i let go

**Comment by Lowentwickler** [comment]
Try to hover mouse over the sidebar, then hold right button and move.

**Comment by QuantumEntangledAndy** [comment]
> Try to hover mouse over the sidebar, then hold right button and move.

That dosen't move the camera for me

**Comment by QuantumEntangledAndy** [comment]
https://user-images.githubusercontent.com/13386481/148196118-0d8c61e9-2a34-4a21-9472-02b18ac86296.mp4

**Pull request merged**
